import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Header } from './_layouts/header'
import { Footer } from './_layouts/footer'
import { ReactQueryProvider } from '@/assets/lib/react-query'
import { Toaster } from 'sonner'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <ReactQueryProvider>
          <Header />
          <Toaster closeButton richColors />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
